services:
  redis-master:
    image: redis:7.2
    container_name: redis-master
    restart: always
    command: ["redis-server", "/redis-conf/redis-master.conf"]
    volumes:
      - redis-master-data:/data
      - ./redis-conf/redis-master.conf:/redis-conf/redis-master.conf
    ports:
      - "6379:6379"
    networks:
      - redis-net

  redis-replica-1:
    image: redis:7.2
    container_name: redis-replica-1
    restart: always
    command: ["redis-server", "/redis-conf/redis-replica.conf"]
    volumes:
      - redis-replica-1-data:/data
      - ./redis-conf/redis-replica.conf:/redis-conf/redis-replica.conf
    depends_on:
      - redis-master
    networks:
      - redis-net

  redis-replica-2:
    image: redis:7.2
    container_name: redis-replica-2
    restart: always
    command: ["redis-server", "/redis-conf/redis-replica.conf"]
    volumes:
      - redis-replica-2-data:/data
      - ./redis-conf/redis-replica.conf:/redis-conf/redis-replica.conf
    depends_on:
      - redis-master
    networks:
      - redis-net

  sentinel-1:
    image: redis:7.2
    container_name: sentinel-1
    restart: always
    command: ["redis-server", "/redis-conf/sentinel.conf", "--sentinel"]
    volumes:
      - ./redis-conf/sentinel.conf:/redis-conf/sentinel.conf
    ports:
      - "26379:26379"
    networks:
      - redis-net

  sentinel-2:
    image: redis:7.2
    container_name: sentinel-2
    restart: always
    command: ["redis-server", "/redis-conf/sentinel.conf", "--sentinel"]
    volumes:
      - ./redis-conf/sentinel.conf:/redis-conf/sentinel.conf
    ports:
      - "26380:26379"
    networks:
      - redis-net

  sentinel-3:
    image: redis:7.2
    container_name: sentinel-3
    restart: always
    command: ["redis-server", "/redis-conf/sentinel.conf", "--sentinel"]
    volumes:
      - ./redis-conf/sentinel.conf:/redis-conf/sentinel.conf
    ports:
      - "26381:26379"
    networks:
      - redis-net

  go-app:
    build: ./go-app
    container_name: go-app
    depends_on:
      - redis-master
      - sentinel-1
      - sentinel-2
      - sentinel-3
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge

volumes:
  redis-master-data:
  redis-replica-1-data:
  redis-replica-2-data:
